"""SQLAlchemy ORM models for OffroadTrip.

Extended from selfdrivetrip with off-road / nature / history / douyin fields.
9 tables: Route, DayPlan, RouteSegment, POI, Meal, Hotel, WeatherForecast,
          StoryCard, DouyinLink, SavedSearch
"""

import uuid
from datetime import datetime

from sqlalchemy import (
    Column,
    String,
    Integer,
    Float,
    DateTime,
    ForeignKey,
    Text,
    Boolean,
    JSON,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database import Base


def _uuid():
    return str(uuid.uuid4())


# Use UUID for PostgreSQL, String for SQLite (dev fallback)
def _id_type():
    """Return the right column type for primary keys based on DB backend."""
    from app.config import settings

    if settings.use_sqlite:
        return String(36)
    return UUID(as_uuid=False)


IDType = _id_type()


class Route(Base):
    """A complete trip route with multiple day plans."""

    __tablename__ = "routes"

    id = Column(IDType, primary_key=True, default=_uuid)
    share_id = Column(String(16), unique=True, nullable=False, index=True)
    title = Column(String(255), nullable=False)
    departure = Column(String(255), nullable=False)
    destination = Column(String(255), nullable=False)
    total_distance = Column(Float, default=0.0)
    total_duration = Column(Float, default=0.0)  # hours

    # Trip classification
    trip_type = Column(String(50), default="越野自驾")  # 越野自驾/轻度越野/自驾游
    theme = Column(String(100), default="回归自然")
    vehicle_type = Column(String(50), default="SUV")  # SUV/越野车/轿车/新能源

    # ★ Off-road specific scores (1-5)
    terrain_difficulty = Column(Integer, default=2)  # 1=easy 5=hard off-road
    nature_score = Column(Integer, default=4)  # 1-5 natural scenery richness

    # People & budget
    adults = Column(Integer, default=2)
    children = Column(Integer, default=0)
    budget = Column(Float, default=0.0)
    status = Column(String(20), default="draft")  # draft / published

    # ★ Overall travel tips (generated by agent)
    overall_tips = Column(Text, default="")

    created_at = Column(DateTime, default=datetime.utcnow)
    view_count = Column(Integer, default=0)

    day_plans = relationship(
        "DayPlan", back_populates="route", cascade="all, delete-orphan",
        order_by="DayPlan.day_number",
    )
    weather_forecasts = relationship(
        "WeatherForecast", back_populates="route", cascade="all, delete-orphan"
    )
    story_cards = relationship(
        "StoryCard", back_populates="route", cascade="all, delete-orphan"
    )


class DayPlan(Base):
    """One day's itinerary within a route."""

    __tablename__ = "day_plans"

    id = Column(IDType, primary_key=True, default=_uuid)
    route_id = Column(IDType, ForeignKey("routes.id", ondelete="CASCADE"), nullable=False)
    day_number = Column(Integer, nullable=False)
    date = Column(String(20), default="")  # e.g. "2026-07-08" or "第1天"
    theme = Column(String(100), default="")
    day_distance = Column(Float, default=0.0)  # km
    day_duration = Column(Float, default=0.0)  # hours
    day_cost = Column(Float, default=0.0)

    # ★ Extended fields
    weather_advisory = Column(Text, default="")  # 天气出行建议
    scenery_description = Column(Text, default="")  # 沿路风景描述
    terrain_note = Column(Text, default="")  # 路况说明 (铺装/非铺装/越野)

    route = relationship("Route", back_populates="day_plans")
    segments = relationship(
        "RouteSegment", back_populates="day_plan", cascade="all, delete-orphan",
        order_by="RouteSegment.sort_order",
    )
    pois = relationship(
        "POI", back_populates="day_plan", cascade="all, delete-orphan",
        order_by="POI.sort_order",
    )
    meals = relationship("Meal", back_populates="day_plan", cascade="all, delete-orphan")
    hotels = relationship("Hotel", back_populates="day_plan", cascade="all, delete-orphan")


class RouteSegment(Base):
    """A driving segment between two points in a day."""

    __tablename__ = "route_segments"

    id = Column(IDType, primary_key=True, default=_uuid)
    day_plan_id = Column(IDType, ForeignKey("day_plans.id", ondelete="CASCADE"), nullable=False)
    from_name = Column(String(255), nullable=False)
    to_name = Column(String(255), nullable=False)
    distance = Column(Float, default=0.0)  # km
    duration = Column(Float, default=0.0)  # hours
    toll_cost = Column(Float, default=0.0)
    fuel_cost = Column(Float, default=0.0)
    polyline = Column(JSON, default=list)  # [[lat, lng], ...] decoded
    sort_order = Column(Integer, default=0)

    day_plan = relationship("DayPlan", back_populates="segments")
    pois = relationship(
        "POI", back_populates="segment", cascade="all, delete-orphan",
        order_by="POI.sort_order",
    )


class POI(Base):
    """A point of interest - scenic spot, viewpoint, gas station, etc."""

    __tablename__ = "pois"

    id = Column(IDType, primary_key=True, default=_uuid)
    day_plan_id = Column(IDType, ForeignKey("day_plans.id", ondelete="CASCADE"), nullable=False)
    segment_id = Column(IDType, ForeignKey("route_segments.id", ondelete="SET NULL"), nullable=True)

    type = Column(String(30), nullable=False)  # scenic/nature/history/food/viewpoint/gas_station/hotel
    # ★ category for richer classification
    category = Column(String(30), default="scenic")  # scenic/nature/history/food/viewpoint/waypoint
    name = Column(String(255), nullable=False)
    lat = Column(Float, default=0.0)
    lng = Column(Float, default=0.0)
    rating = Column(Float, default=0.0)
    price_level = Column(String(20), default="")
    image_url = Column(Text, default="")
    description = Column(Text, default="")
    source_url = Column(Text, default="")
    booking_url = Column(Text, default="")
    duration_minutes = Column(Integer, default=0)
    sort_order = Column(Integer, default=0)

    # ★ Extended: why this spot is special
    feature = Column(Text, default="")  # 特色说明 - why worth visiting
    anecdote = Column(Text, default="")  # 趣事/典故
    historical_figure = Column(String(255), default="")  # 相关历史人物
    historical_event = Column(Text, default="")  # 相关历史事件

    day_plan = relationship("DayPlan", back_populates="pois")
    segment = relationship("RouteSegment", back_populates="pois")


class Meal(Base):
    """A meal recommendation."""

    __tablename__ = "meals"

    id = Column(IDType, primary_key=True, default=_uuid)
    day_plan_id = Column(IDType, ForeignKey("day_plans.id", ondelete="CASCADE"), nullable=False)
    type = Column(String(20), nullable=False)  # breakfast/lunch/dinner
    restaurant_name = Column(String(255), nullable=False)
    cuisine_type = Column(String(100), default="")
    cost_per_person = Column(Float, default=0.0)
    image_url = Column(Text, default="")
    rating = Column(Float, default=0.0)
    recommendation = Column(Text, default="")

    # ★ Extended
    is_local_specialty = Column(Boolean, default=False)  # 是否地方特色
    story = Column(Text, default="")  # 美食背后的故事
    image_urls = Column(JSON, default=list)  # multiple photos

    day_plan = relationship("DayPlan", back_populates="meals")


class Hotel(Base):
    """A hotel recommendation."""

    __tablename__ = "hotels"

    id = Column(IDType, primary_key=True, default=_uuid)
    day_plan_id = Column(IDType, ForeignKey("day_plans.id", ondelete="CASCADE"), nullable=False)
    name = Column(String(255), nullable=False)
    lat = Column(Float, default=0.0)
    lng = Column(Float, default=0.0)
    price_per_night = Column(Float, default=0.0)
    rating = Column(Float, default=0.0)
    image_url = Column(Text, default="")
    booking_url = Column(Text, default="")
    address = Column(Text, default="")
    phone = Column(String(50), default="")

    day_plan = relationship("DayPlan", back_populates="hotels")


class WeatherForecast(Base):
    """Weather forecast for a city along the route."""

    __tablename__ = "weather_forecasts"

    id = Column(IDType, primary_key=True, default=_uuid)
    route_id = Column(IDType, ForeignKey("routes.id", ondelete="CASCADE"), nullable=False)
    city_name = Column(String(255), nullable=False)
    date = Column(String(20), nullable=False)
    temperature_high = Column(Float, default=0.0)
    temperature_low = Column(Float, default=0.0)
    weather_condition = Column(String(100), default="")
    icon = Column(String(50), default="")
    humidity = Column(Float, default=0.0)
    wind_speed = Column(Float, default=0.0)
    # ★ precipitation for off-road decisions
    precipitation = Column(Float, default=0.0)  # mm

    route = relationship("Route", back_populates="weather_forecasts")


class StoryCard(Base):
    """★ Independent history / culture story card.

    Generated by the history agent - figures, events, anecdotes for cities along the route.
    """

    __tablename__ = "story_cards"

    id = Column(IDType, primary_key=True, default=_uuid)
    route_id = Column(IDType, ForeignKey("routes.id", ondelete="CASCADE"), nullable=False)
    related_city = Column(String(255), default="")
    day_number = Column(Integer, default=0)  # which day this story belongs to (0 = route-level)

    figure = Column(String(255), default="")  # 历史人物
    event = Column(String(255), default="")  # 历史事件
    anecdote = Column(String(255), default="")  # 趣事标题
    story_text = Column(Text, default="")  # 完整故事
    image_url = Column(Text, default="")

    route = relationship("Route", back_populates="story_cards")


class DouyinLink(Base):
    """★ Douyin (TikTok) search link for a POI / meal / story.

    Since Douyin has no public search API, we generate search keywords + deep links.
    Users tap to jump to Douyin app search.
    """

    __tablename__ = "douyin_links"

    id = Column(IDType, primary_key=True, default=_uuid)
    route_id = Column(IDType, ForeignKey("routes.id", ondelete="CASCADE"), nullable=False)
    related_type = Column(String(30), nullable=False)  # poi / meal / story / city
    related_id = Column(String(36), default="")  # FK to the related entity
    keyword = Column(String(255), nullable=False)  # search keyword
    search_url = Column(Text, default="")  # https://www.douyin.com/search/xxx
    qr_code_data = Column(Text, default="")  # data for QR code generation
    label = Column(String(100), default="")  # display label e.g. "看抖音视频"


class SavedSearch(Base):
    """Saved search query for analytics."""

    __tablename__ = "saved_searches"

    id = Column(IDType, primary_key=True, default=_uuid)
    session_id = Column(String(255), default="", index=True)
    departure_city = Column(String(255), nullable=False)
    destination_city = Column(String(255), nullable=False)
    start_date = Column(String(20), default="")
    days = Column(Integer, default=3)
    trip_type = Column(String(50), default="越野自驾")
    adults = Column(Integer, default=2)
    children = Column(Integer, default=0)
    vehicle_type = Column(String(50), default="SUV")
    budget = Column(Float, default=0.0)
    theme = Column(String(100), default="")
    created_at = Column(DateTime, default=datetime.utcnow)
